Formatting and cosmetical changes for the navigation code (#347)
### Motivation

Locally executed navigation tests produce two failures:

```
FAILED tests/test_navigation.py::test_straight_line_with_high_angles - TimeoutError: condition took more than 100 s
FAILED tests/test_navigation.py::test_driving_to_exact_positions - TimeoutError: condition took more than 100 s
```

### Implementation

I fixed some formatting, added a epsilon to the StraightLineNavigation
"should_stop" and switched back to normal driving speed for the exact
positions test.

### Progress

- [x] I chose a meaningful title that completes the sentence: "If
applied, this PR will..."
- [x] I chose meaningful labels (if GitHub allows me to so).
- [x] The implementation is complete.
- [x] Pytests have been added (or are not necessary).